### ISSUE TITLE
Inverted images when using letterbox

### ISSUE THREAD

**Issue by jakubjo** [spacecatninja/craft-imager-x#147]
There seems to be an issue regarding transforming _some_ images using the letterbox transform.

Uploading & transforming [one of the source images](https://github.com/spacecatninja/craft-imager-x/files/8592929/imager-x-source.zip) results in an [image with inverted colors](https://github.com/spacecatninja/craft-imager-x/files/8592928/imager-x-results.zip).

### The transform settings are as follows:

- width: 970
- height: 600
- mode: "letterbox"
- format: "jpg"

### Config settings are:

`convertToRGB` is set to `true` in the config file. We also tried adding `preserveColorProfiles` with a value of `true` to the config. It didn't made any difference.

### Additional info

- Imager version & edition: `v3.5.6.1 [PRO]`
- Imager transformer:
- Craft version: `Craft Pro 3.7.37`
- PHP version: `8.0.17`
- Image driver & version: `Imagick 3.7.0 (ImageMagick 7.1.0-16)`
- Database driver & version: `MySQL 5.7.37`

### Some hints

- Both images are CMYK -- Imager does indeed convert them to RGB
- Both images contain a Color Profile: `Coated FOGRA39 (ISO 12647-2:2004)`
  - Minifying the image using something like https://imagecompressor.com does not change the outcome
- Removing the `letterbox` mode resolves the issue with inverted colors

**Comment by aelvan** [comment]
Wow, that's an interesting one. 🤨 

I'll have a look and see if there's a way to make Imagick behave.

**Comment by aelvan** [comment]
@jakubjo You have `preserveCmykColorspace` set to `true` in the Craft config?

**Comment by aelvan** [comment]
Should be fixed in 3.5.8. 

The issue was that when creating the letterbox, a new image with the correct background color is created, and then the transformed image is pasted into it. The new image was always created as RGB, so pasting a CMYK image into that one distorted the colors. The letterbox method will now set the palette of the new image to the same as the transformed image, or RGB if `convertToRGB` is set to `true`. 

This gives me what looks like the correct results. If I have `convertToRGB` set to `true`, I get an image that in the browser matches the original image when viewed for instance in preview or photoshop. If `convertToRGB` is set to `false`, I get an image that looks slightly greyish when viewed in the browser, which is because the image has a cmyk profile (I see the same when opening your source images in the browser).

Worth noting that having `preserveCmykColorspace` set to `false` in Craft's config, would've avoided this since the image would've been converted to RGB on upload. But I assume that you've set this to true for a reason, so. :)

**Comment by jakubjo** [comment]
Wow, that was insanely fast. Great job, thanks! 

Will check back with the team why `preserveCmykColorspace` is set to `true`.

**Comment by jakubjo** [comment]
Unfortunately the issue still exists when using a mode which is not `letterbox`. 

See the following screenshots where I've used GQL to create a transform.

- The [first screenshot](https://user-images.githubusercontent.com/2873852/169888028-0834b3f9-f30b-4ca3-89ed-779fd7c7fdf2.png) shows a transform using the `letterbox` mode -- the issue with this one is the one you've fixed in [#ef228d6](https://github.com/spacecatninja/craft-imager-x/commit/ef228d644d62a44b71b5b803f3df27daf71e49b0)
- The [second screenshot](https://user-images.githubusercontent.com/2873852/169888132-a69fadc4-7f58-4671-8a2a-54cabfc91f19.png) shows a transform of the same image using no dedicated mode -- rendered with inverted colors.

**Comment by aelvan** [comment]
Not able to reproduce. Did you open the transform in your browser to confirm that it actually looks like that? That GraphQL preview sometimes is a bit wonky.

Can you provide your general.php and imager-x.php config files (make sure to redact anything sensitive).

**Comment by jakubjo** [comment]
Unfortunately we've detected the issue in regular twig views. I used GraphQL to verify the issue by quickly switching modes & dimensions and also to make sure the image was not cached. That's also the reason you see the height of `603`. ;)


<details>

<summary>
general.php (Click me)
</summary>

```php
<?php
return [
    // Global settings
    '*' => [
        'defaultWeekStartDay' => 1,

        'omitScriptNameInUrls' => true,

        'limitAutoSlugsToAscii' => true,

        'cookieValidationKey' => 'space-cat',

        'securityKey' => 'space-cat',

        'convertFilenamesToAscii' => true,

        'sendPoweredByHeader' => false,

        'useEmailAsUsername' => true,

        'runQueueAutomatically' => true,

        'maxUploadFileSize' => '3072M',

        'enableCsrfProtection' => false,

        'defaultCookieDomain' => env('DEFAULT_COOKIE_DOMAIN', $_SERVER['SERVER_NAME']),

        'requireUserAgentAndIpForSession' => false,

        'useProjectConfigFile' => true,

        'addTrailingSlashesToUrls' => true,

        'allowAdminChanges' => true,

        'devMode' => App::env('ENVIRONMENT') === 'dev',

        'enableTemplateCaching' => false,

        'extraFileKinds' => [
            'podcast' => [
                'label' => 'Podcast',
                'extensions' => ['mp3','ogg'],
            ],
        ],

        'preserveCmykColorspace' => true,

    ],
    'dev' => [
        'allowAdminChanges' => true,
        'runQueueAutomatically' => false,
    ],
    // Staging environment settings
    'staging' => [
        //'cpTrigger' => null,
        'allowAdminChanges' => true,
        'runQueueAutomatically' => false,
    ],

    // Production environment settings
    'production' => [
        // 'cpTrigger' => null,
        'enableCsrfProtection' => true,
        'allowAdminChanges' => true,
        'runQueueAutomatically' => false,
    ],
];
```
</details>



<details>

<summary>
imager-x.php (Click me)
</summary>

```php
<?php

return [
    'cacheDurationRemoteFiles' => 60*60*24, // 1 day
    'suppressExceptions' => true,
    'convertToRGB' => true,

    // The default asset ID which is used when an image transform fails due to some reason.
    // https://imager-x.spacecat.ninja/configuration.html#fallbackimage-int-string-asset
    // TODO: Change this to a slightly different version when implementing final version of ********.
    'fallbackImage' => 393118,

    // We need to add WebP image format to safe file formats.
    // Otherwise imager-x won't transform WebP images in GQL-Queries.
    // https://imager-x.spacecat.ninja/configuration.html#safefileformats-array
    'safeFileFormats' => ['jpg', 'jpeg', 'gif', 'png', 'webp'],

    // Set bgColor to white, so potential PNG transparencies are rendered
    // with a white background when transformed to non transparent images, like jpgs.
    // https://imager-x.spacecat.ninja/configuration.html#bgcolor-string
    'bgColor' => '#ffffff',
];

```
</details>

**Comment by jakubjo** [comment]
Replacing the file resolved the issue. 
Will need to check back with the colleague who uploaded the file. He's currently on vacation, so this will take approx. two weeks. I'll report here when I have some more information what might help us to reproduce the issue.

Thank you for your investigations.
